name: prim_sistem
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_picker: ^2.1.0
  get:
    # add this line to your dependencies


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
